#!/bin/bash

set -e -x

cd sn_api
rm -f fake_node_data.json
cargo test --lib --release --features=scl-mock -- --test-threads=1
rm -f fake_node_data.json
cargo test --doc --release --features=scl-mock -- --test-threads=1
cd -
