#!/bin/bash

set -e -x

function run_api_tests() {
    cd sn_api
    TEST_AUTH_CREDENTIALS=$(cat ~/.local/share/safe-cli/credentials)
    cargo test --release --lib -- --test-threads=1
    cd -
}

run_api_tests
