#!/bin/bash

set -e -x

function run_api_tests() {
    cd sn_api
    export TEST_AUTH_CREDENTIALS=$(cat ~/.safe/cli/credentials)
    #cargo test --release --lib -- --test-threads=1
    cargo test --release test_sequence_ -- --test-threads=1
    cargo test --release test_fetch_ -- --test-threads=1
    cargo test --release test_keys_ -- --test-threads=1
    cargo test --release test_safeurl_ -- --test-threads=1
    cargo test --release test_wallet_ -- --test-threads=1
    # we keep the following tests temporarily disabled in CI
    #cargo test --release test_nrs_ -- --test-threads=1
    #cargo test --release test_files_ -- --test-threads=1
    cd -
}

run_api_tests
