#!/bin/bash

set -e -x

function run_api_tests() {
    cd sn_api
    TEST_AUTH_CREDENTIALS=$(cat ~/.safe/cli/credentials)
    cargo test --release --lib --features=simulated-payouts -- --test-threads=1
    cd -
}

run_api_tests
