#!/bin/bash

set -e -x

function run_cli_tests() {
    cd safe-cli
    cargo test --release --test cli_cat -- --test-threads=1
    cargo test --release --test cli_dog -- --test-threads=1
    cargo test --release --test cli_files -- --test-threads=1
    cargo test --release --test cli_files_get -- --test-threads=1
    cargo test --release --test cli_keys -- --test-threads=1
    cargo test --release --test cli_wallet -- --test-threads=1
    cargo test --release --test cli_nrs -- --test-threads=1
    cd -
}

run_cli_tests
