#!/bin/bash
# This script will not work if called individually.
# The integration tests require the auth daemon to be running.
# It's better to either run the all-tests script or call Makefile targets.

set -e -x

# HACK: evade MacOs catalina libsodium error
if [[ "$OSTYPE" == "darwin"* ]]; then
	brew install libsodium
	brew install pkg-config

	export RUST_SODIUM_USE_PKG_CONFIG=1
fi

function run_cli_tests() {
    cd safe-cli
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_cat -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_dog -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_files -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_keys -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_wallet -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_nrs -- --test-threads=1
    cd -
}

# run the integration tests but without fake-auth, using the safe-authd to get credentials
function run_cli_tests_with_auth_daemon() {
    cd safe-cli
    # create account
    echo "Creating account by sending auth request to port:" $RANDOM_PORT_NUMBER
    SAFE_AUTHD_PATH=$SAFE_MOCK_VAULT_PATH SAFE_AUTH_PASSPHRASE=a SAFE_AUTH_PASSWORD=b cargo run \
    --release --features=mock-network -- auth create-acc --test-coins # --endpoint $RANDOM_PORT_NUMBER

    # get auth credentials which will be then used by the integration tests to connect to mock-network
    echo "Logging in by sending auth request to port:" $RANDOM_PORT_NUMBER
    SAFE_AUTHD_PATH=$SAFE_MOCK_VAULT_PATH SAFE_AUTH_PASSPHRASE=a SAFE_AUTH_PASSWORD=b cargo run \
    --release --features=mock-network -- auth login --self-auth # --endpoint $RANDOM_PORT_NUMBER

    cargo test --release --features=mock-network --test cli_cat -- --test-threads=1
    cargo test --release --features=mock-network --test cli_dog -- --test-threads=1
    cargo test --release --features=mock-network --test cli_files -- --test-threads=1
    cargo test --release --features=mock-network --test cli_keys -- --test-threads=1
    cargo test --release --features=mock-network --test cli_wallet -- --test-threads=1
    cargo test --release --features=mock-network --test cli_nrs -- --test-threads=1
    cd -
}

run_cli_tests
# Temporarily diasable these tests until we migrate to GH Actions setup for CI
# run_cli_tests_with_auth_daemon
