#!/bin/bash

set -e -x

function run_cli_tests() {
    cd safe-cli
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_cat -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_dog -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_files -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_keys -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_wallet -- --test-threads=1
    rm -f fake_vault_data.json
    cargo test --release --features=scl-mock --test cli_nrs -- --test-threads=1
    cd -
}

run_cli_tests
