#!/bin/bash

set -e -x
source ./resources/test-scripts/run-authd-mock

# run the integration tests but without fake-auth,
# using the safe-authd to get credentials and against mock network
function run_cli_tests_with_auth_daemon_with_mock() {
    cd safe-cli
    passphrase=${RANDOM:0:6}
    password=${RANDOM:0:6}
    # create account
    echo "Creating account by sending 'create-acc' request to authd..."
    SAFE_AUTH_PASSPHRASE=$passphrase SAFE_AUTH_PASSWORD=$password cargo run \
    --release --features mock-network \
    -- auth create-acc --test-coins

    # get auth credentials which will be then used by the integration tests to connect to mock-network
    echo "Logging in by sending 'login' request to authd:"
    SAFE_AUTH_PASSPHRASE=$passphrase SAFE_AUTH_PASSWORD=$password cargo run \
    --release --features mock-network \
    -- auth login --self-auth

    echo "Run let's run the CLI integration tests..."
    cargo test --release --features mock-network --test cli_cat
    cargo test --release --features mock-network --test cli_dog
    cargo test --release --features mock-network --test cli_files -- --test-threads=1
    cargo test --release --features mock-network --test cli_files_get -- --test-threads=1
    cargo test --release --features mock-network --test cli_keys
    cargo test --release --features mock-network --test cli_wallet
    cargo test --release --features mock-network --test cli_nrs
    cd -
}

build_safe_authd_with_mock
run_safe_authd_with_mock
run_cli_tests_with_auth_daemon_with_mock
