#!/bin/bash

set -e -x

[[ -z $SAFE_AUTHD_MOCK_PATH ]] && export SAFE_AUTHD_MOCK_PATH=~/safe-authd-with-mock
[[ -z $SAFE_MOCK_VAULT_PATH ]] && export SAFE_MOCK_VAULT_PATH=$SAFE_AUTHD_MOCK_PATH

uname_output=$(uname -a)
authd_bin_name="safe-authd"
case $uname_output in
    MSYS_NT*)   # Windows in Jenkins
        authd_bin_name="safe-authd.exe"
        ;;
    MINGW*)     # Windows in GH Actions
        authd_bin_name="safe-authd.exe"
        ;;
esac

function build_safe_authd_with_mock() {
    cd safe-authd
    cargo build --release --features mock-network

    rm -rf $SAFE_AUTHD_MOCK_PATH
    mkdir $SAFE_AUTHD_MOCK_PATH
    mv ../target/release/$authd_bin_name $SAFE_AUTHD_MOCK_PATH
    pwd
    cd -
}

function run_safe_authd_with_mock() {
    cd $SAFE_AUTHD_MOCK_PATH

    # this won't have any effect on Linux/Mac, but it's required for Windows
    ./$authd_bin_name install || true

    echo "Stopping safe-authd daemon.."
    ./$authd_bin_name stop || true

    echo "Launching safe-authd daemon..."
    ./$authd_bin_name start
    sleep 15
    cd -
}
