#!/bin/bash

set -e -x

authd_bin_name="safe-authd"
[[ -z $RANDOM_PORT_NUMBER ]] && export RANDOM_PORT_NUMBER=41805
[[ -z $SAFE_MOCK_VAULT_PATH ]] && export SAFE_MOCK_VAULT_PATH=~/safe_auth

function build_safe_authd() {
    cd safe-authd
    cargo build --release --features mock-network

    uname_output=$(uname -a)
    case $uname_output in
        Linux*)
            ;;
        Darwin*)
            ;;
        MSYS_NT*)
            authd_bin_name="safe-authd.exe"
            ;;
        *)
            echo "Platform not supported. Please extend to support this platform."
            exit 1
    esac
    rm -rf $SAFE_MOCK_VAULT_PATH
    mkdir $SAFE_MOCK_VAULT_PATH
    mv ../target/release/$authd_bin_name $SAFE_MOCK_VAULT_PATH

    cd -
}

function run_safe_authd() {
    cd $SAFE_MOCK_VAULT_PATH
    ./$authd_bin_name stop || true
    echo "Launching safe_auth daemon on port:" $RANDOM_PORT_NUMBER
    # ./target/release/$authd_bin_name start --listen https://localhost:$RANDOM_PORT_NUMBER &
    ./$authd_bin_name start &
    sleep 15
    cd -
}

build_safe_authd
run_safe_authd
