#!/bin/sh
#
# Any update to this file will require erasing the githook locally on your machine
# and running cargo test to install it again
set -e

echo 'PrePush: cargo clippy -- -D warnings'
cargo clippy -- -D warnings
echo 'PrePush: cargo fmt -- --check'
cargo fmt -- --check
