#!/usr/bin/env bash

if [[ -z "$build_type" ]]; then
    echo "build_type must be set to prod or dev"
    exit 1
fi

if [[ -z "$build_target" ]]; then
    echo "target must be set to x86_64-linux-android or armv7-linux-androideabi"
    exit 1
fi

if [[ "$build_type" == "dev" ]]; then
    cargo build --features=mock-network \
        --release --lib --manifest-path=safe_authenticator/Cargo.toml --target="$build_target"
    cargo build --features=mock-network \
        --release --lib --manifest-path=safe_app/Cargo.toml --target="$build_target"
else
    cargo build --release --lib --manifest-path=safe_authenticator/Cargo.toml --target="$build_target"
    cargo build --release --lib --manifest-path=safe_app/Cargo.toml --target="$build_target"
fi
