#!/bin/bash

cargo check --verbose --manifest-path=safe_core/Cargo.toml &&
cargo check --verbose --features=testing --lib --tests --manifest-path=safe_core/Cargo.toml &&
cargo check --verbose --features=testing --lib --tests --manifest-path=safe_authenticator/Cargo.toml &&
cargo check --verbose --features=testing --lib --tests --manifest-path=safe_app/Cargo.toml &&
cargo check --verbose --lib --tests --manifest-path=tests/Cargo.toml
