#!/bin/bash

cargo check --verbose --features=use-mock-routing --release --manifest-path=safe_core/Cargo.toml &&
cargo check --verbose --features="testing use-mock-routing" --release --lib --tests --manifest-path=safe_core/Cargo.toml &&
cargo check --verbose --features="testing use-mock-routing" --release --lib --tests --manifest-path=safe_authenticator/Cargo.toml &&
cargo check --verbose --features="testing use-mock-routing" --release --lib --tests --manifest-path=safe_app/Cargo.toml
