#!/bin/bash

cd safe_core && cargo clippy --profile=test --features=use-mock-routing && cd .. &&
cd safe_authenticator && cargo clippy --profile=test --features=use-mock-routing && cd .. &&
cd safe_app && cargo clippy --profile=test --features=use-mock-routing && cd ..
