#!/bin/bash

set -x;

cd safe_core && cargo clippy --verbose --features=testing --all-targets && cd .. &&
cd safe_authenticator && cargo clippy --verbose --features=testing --all-targets && cd .. &&
cd safe_app && cargo clippy --verbose --features=testing --all-targets && cd .. &&
cd tests && cargo clippy --verbose --all-targets && cd ..
