#!/bin/bash

set -x;

# TODO: remove `check-all` line below.
# This fixes a Clippy issue when compiling JNI dependency by running `cargo check` first.
# See https://github.com/rust-lang-nursery/rust-clippy/issues/2831
scripts/check-all &&
  # scripts/clippy-real &&
  scripts/clippy-mock
