#!/bin/bash

set -x;

cd safe_core && cargo clippy --verbose --features="use-mock-routing" --release --profile=test && cd .. &&
cd safe_authenticator && cargo clippy --verbose --features="use-mock-routing" --release --profile=test && cd .. &&
cd safe_app && cargo clippy --verbose --features="use-mock-routing" --release --profile=test && cd ..
