#!/bin/bash

set -e -x

rm -rf images
mkdir images

cargo install cargo-deps

cargo deps --all-deps --include-orphans --subgraph safe_app safe_authenticator safe_authenticator_ffi safe_core --subgraph-name "SAFE Client Libs" --filter safe-nd quic-p2p ffi_utils safe_app safe_authenticator safe_authenticator_ffi safe_bindgen safe_core self_encryption --manifest-path safe_app/Cargo.toml | dot -Tpng -Nfontname=Iosevka -Gfontname=Iosevka > images/safe-client-libs.png
