#!/bin/bash

# This script is a wrapper for running the packaging in the context of a container.
#
# It is assuming there will be an 'artifacts' directory that contains all of the
# pre-built versions of safe_authenticator and safe_app for Linux and targetX, and
# hopefully Windows in the future.
#
# With all the artifacts available it will package everything into zip files.

set -e -x

is_versioned=$1
if [[ -z "$is_versioned" ]]; then
    echo "A true/false argument must be passed indicating to package for a versioned deployment."
    exit 1
fi

if [[ ! -d "artifacts" ]]; then
    echo "This script is intended to be used with a docker container and a set of pre-built artifacts."
    echo "Place these artifacts in an 'artifacts' folder at the root of the reptargetitory and perform the 'docker run' command again."
    exit 1
fi

export RUST_BACKTRACE=1
[[ ! -d "deploy" ]] && mkdir -p deploy/real deploy/mock

declare -a targets=(\
    "x86_64-unknown-linux-gnu" "x86_64-pc-windows-gnu" "x86_64-apple-darwin" \
    "armv7-linux-androideabi" "x86_64-linux-android" "x86_64-apple-ios" \
    "aarch64-apple-ios" "apple-ios")
for target in "${targets[@]}"; do
    pwd
    if [[ $is_versioned == "true" ]]; then
        ./scripts/package.rs --lib \
            --name safe_app \
            --dest deploy/mock \
            --target "$target" \
            --artifacts "artifacts/mock" \
            --mock
        ./scripts/package.rs --lib \
            --name safe_app \
            --dest deploy/real \
            --target "$target" \
            --artifacts "artifacts/real"
        ./scripts/package.rs --lib \
            --name safe_authenticator \
            --dest deploy/mock \
            --target "$target" \
            --artifacts "artifacts/mock" \
            --mock
        ./scripts/package.rs --lib \
            --name safe_authenticator \
            --dest deploy/real \
            --target "$target" \
            --artifacts "artifacts/real"
    else
        ./scripts/package.rs --lib \
            --name safe_app \
            --dest deploy/mock \
            --target "$target" \
            --artifacts "artifacts/mock" \
            --mock \
            --commit
        ./scripts/package.rs --lib \
            --name safe_app \
            --dest deploy/real \
            --target "$target" \
            --artifacts "artifacts/real" \
            --commit
        ./scripts/package.rs --lib \
            --name safe_authenticator \
            --dest deploy/mock \
            --target "$target" \
            --artifacts "artifacts/mock" \
            --mock \
            --commit
        ./scripts/package.rs --lib \
            --name safe_authenticator \
            --dest deploy/real \
            --target "$target" \
            --artifacts "artifacts/real" \
            --commit
    fi
done
