#!/bin/bash

# This script is a wrapper for running the packaging in the context of a container.
#
# It is assuming there will be an 'artifacts' directory that contains all of the
# pre-built versions of safe_authenticator and safe_app for Linux and OSX, and
# hopefully Windows in the future.
#
# With all the artifacts available it will package everything into zip files.

set -e -x

is_versioned=$1
if [[ -z "$is_versioned" ]]; then
    echo "A true/false argument must be passed indicating to package for a versioned deployment."
    exit 1
fi

if [[ ! -d "artifacts" ]]; then
    echo "This script is intended to be used with a docker container and a set of pre-built artifacts."
    echo "Place these artifacts in an 'artifacts' folder at the root of the repository and perform the 'docker run' command again."
    exit 1
fi

export RUST_BACKTRACE=1
[[ ! -d "deploy" ]] && mkdir -p deploy/real deploy/mock

declare -a operating_systems=("linux" "win" "osx")
for os in "${operating_systems[@]}"; do
    pwd
    if [[ $is_versioned == "true" ]]; then
        ./scripts/package.rs --lib \
            --name safe_app \
            --dest deploy/mock \
            --arch "$os-x64" \
            --artifacts "artifacts/$os/mock" \
            --mock
        ./scripts/package.rs --lib \
            --name safe_app \
            --dest deploy/real \
            --arch "$os-x64" \
            --artifacts "artifacts/$os/real"
        ./scripts/package.rs --lib \
            --name safe_authenticator \
            --dest deploy/mock \
            --arch "$os-x64" \
            --artifacts "artifacts/$os/mock" \
            --mock
        ./scripts/package.rs --lib \
            --name safe_authenticator \
            --dest deploy/real \
            --arch "$os-x64" \
            --artifacts "artifacts/$os/real"
    else
        ./scripts/package.rs --lib \
            --name safe_app \
            --dest deploy/mock \
            --arch "$os-x64" \
            --artifacts "artifacts/$os/mock" \
            --mock \
            --commit
        ./scripts/package.rs --lib \
            --name safe_app \
            --dest deploy/real \
            --arch "$os-x64" \
            --artifacts "artifacts/$os/real" \
            --commit
        ./scripts/package.rs --lib \
            --name safe_authenticator \
            --dest deploy/mock \
            --arch "$os-x64" \
            --artifacts "artifacts/$os/mock" \
            --mock \
            --commit
        ./scripts/package.rs --lib \
            --name safe_authenticator \
            --dest deploy/real \
            --arch "$os-x64" \
            --artifacts "artifacts/$os/real" \
            --commit
    fi
done
