#!/bin/bash

set -x;

echo "--- Test binary compatibility ---" &&

# Use mock vault file.
unset SAFE_MOCK_IN_MEMORY_STORAGE &&
export SAFE_MOCK_VAULT_PATH=$HOME/tmp &&
mkdir -p "$SAFE_MOCK_VAULT_PATH" &&

export BASE_BRANCH_DIR="${TRAVIS_BUILD_DIR}-$TRAVIS_BRANCH" &&
rsync -av --exclude="target" "${TRAVIS_BUILD_DIR}/" "$BASE_BRANCH_DIR" &&
cp -r "$TRAVIS_BUILD_DIR" "$BASE_BRANCH_DIR" &&

cd "$BASE_BRANCH_DIR" &&
git checkout -qf "$TRAVIS_BRANCH" &&

cd "$TRAVIS_BUILD_DIR" &&
cargo test --verbose --release --features=use-mock-routing --manifest-path=safe_authenticator/Cargo.toml serialisation::write_data -- --ignored &&

cd "$BASE_BRANCH_DIR" &&
cargo test --verbose --release --features=use-mock-routing --manifest-path=safe_authenticator/Cargo.toml serialisation::read_data -- --ignored &&
cargo test --verbose --release --features=use-mock-routing --manifest-path=safe_authenticator/Cargo.toml serialisation::write_data -- --ignored &&

cd "$TRAVIS_BUILD_DIR" &&
cargo test --verbose --release --features=use-mock-routing --manifest-path=safe_authenticator/Cargo.toml serialisation::read_data -- --ignored
