// Copyright 2021 MaidSafe.net limited.
//
// This SAFE Network Software is licensed to you under The General Public License (GPL), version 3.
// Unless required by applicable law or agreed to in writing, the SAFE Network Software distributed
// under the GPL Licence is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. Please review the Licences for the specific language governing
// permissions and limitations relating to use of the SAFE Network Software.

use criterion::Throughput;
use criterion::{criterion_group, criterion_main, Criterion};

use eyre::Result;

use sn_client::{Client, Error};
use sn_interface::{
    messaging::{data::ServiceMsg, AuthKind, Dst, MsgId, ServiceAuth, WireMsg},
    types::register::{Policy, User},
};
use tokio::runtime::Runtime;

use std::collections::BTreeMap;

fn public_policy(owner: User) -> Policy {
    let permissions = BTreeMap::new();
    Policy { owner, permissions }
}

/// Generates a random vector of Dsts using provided `length`.
fn random_vectorof_dsts(length: usize) -> Vec<Dst> {
    let mut dsts = vec![];
    for _i in 0..length {
        dsts.push(Dst {
            name: xor_name::rand::random(),
            section_key: bls::SecretKey::random().public_key(),
        });
    }
    dsts
}

async fn create_client() -> Result<Client, Error> {
    let client = Client::builder().build().await?;

    Ok(client)
}

fn criterion_benchmark(c: &mut Criterion) {
    let mut group = c.benchmark_group("serialize");
    let runtime = Runtime::new().unwrap();

    let client = match runtime.block_on(create_client()) {
        Ok(client) => client,
        Err(err) => {
            println!("Failed to create client with {:?}", err);
            return;
        }
    };

    let (auth, payload, msg_id) = runtime.block_on(async {
        let name = xor_name::rand::random();
        let tag = 15000;
        let owner = User::Key(client.public_key());
        let policy = public_policy(owner);

        let (_address, batch) = match client.create_register(name, tag, policy).await {
            Ok(x) => x,
            Err(error) => panic!("error creating register {error:?}"),
        };

        let client_pk = client.public_key();

        // batch[0].clone()
        // let payload = ServiceMsg::Cmd(batch[0].clone());

        let msg_id = MsgId::new();

        let payload = {
            let msg = ServiceMsg::Cmd(batch[0].clone());
            match WireMsg::serialize_msg_payload(&msg) {
                Ok(payload) => payload,
                Err(error) => panic!("failed to serialise msg payload: {error:?}"),
            }
        };

        let auth = ServiceAuth {
            public_key: client_pk,
            signature: client.sign(&payload),
        };

        let auth = AuthKind::Service(auth);

        // wire_msg parts
        (auth, payload, msg_id)
    });

    let dsts = random_vectorof_dsts(1024);

    // here we determine the size for our throughput measurement.
    let dst = Dst {
        name: xor_name::rand::random(),
        section_key: bls::SecretKey::random().public_key(),
    };
    let the_wire_msg = WireMsg::new_msg(msg_id, payload.clone(), auth.clone(), dst);

    // There's currently no way to reutilize generated bytes
    // so we just use this to get our throughput measurement
    let msg_bytes = match the_wire_msg.serialize() {
        Ok(bytes) => bytes,
        Err(_error) => panic!("Could not serialize the msg bytes"),
    };

    group.throughput(Throughput::Bytes(
        (std::mem::size_of_val(&msg_bytes) * dsts.len()) as u64,
    ));
    // upload and read
    group.bench_with_input(
        "generating bytes to send the same msg to various Dsts",
        &(&dsts, auth, payload, &msg_id),
        |b, (dsts, auth, payload, msg_id)| {
            b.to_async(&runtime).iter(|| async {
                for dst in dsts.iter() {
                    let msg = WireMsg::new_msg(**msg_id, payload.clone(), auth.clone(), *dst);
                    if let Err(_err) = msg.serialize() {
                        panic!("error serialising payload");
                    };
                }

                Ok::<(), Box<dyn std::error::Error>>(())
            });
        },
    );

    group.finish()
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
