# PR workflow.
#
# Runs full suite of checks, with warnings treated as errors.
# Gather code coverage stats and publish them on coveralls.io.

name: Types Changes


on: pull_request

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
 
  data-types-tests:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Data Types Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      # test for changes. (dont use baked in GHA pr/paths filter as then job wont run and we can't require itz)
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/types/**'

              
      # Install Rust
      - uses: actions-rs/toolchain@v1
        id: toolchain
        if: steps.changes.outputs.src == 'true'
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cache.
      - name: Cargo cache registry, index and build
        if: steps.changes.outputs.src == 'true'
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}

      # Run tests.
      - shell: bash
        if: steps.changes.outputs.src == 'true'
        run: cargo test --release types 

      # Print CI machine disk space stats if the tests fail
      - name: Print CI Machine df Stats on Failure
        if: failure()
        run: df -Ph
        shell: bash
